// Generated by FlutterFire CLI for DEV project
// Run: flutterfire configure --project=streak-it-dev --platforms=android --out=lib/core/services/firebase_options_dev.dart

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
    apiKey: 'YOUR_DEV_API_KEY',
    appId: 'YOUR_DEV_APP_ID',
    messagingSenderId: 'YOUR_DEV_SENDER_ID',
    projectId: 'streak-it-dev',
    authDomain: 'streak-it-dev.firebaseapp.com',
    storageBucket: 'streak-it-dev.appspot.com',
  );
}