// Generated by FlutterFire CLI for PROD project
// Run: flutterfire configure --project=streak-it-prod --platforms=android --out=lib/core/services/firebase_options_prod.dart

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
    apiKey: 'YOUR_PROD_API_KEY',
    appId: 'YOUR_PROD_APP_ID',
    messagingSenderId: 'YOUR_PROD_SENDER_ID',
    projectId: 'streak-it-prod',
    authDomain: 'streak-it-prod.firebaseapp.com',
    storageBucket: 'streak-it-prod.appspot.com',
  );
}